src/Entity/Role.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use App\Repository\RoleRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=RoleRepository::class)
 */
class Role
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=20)
     * @Assert\Length(max=20,maxMessage="Le nom du role est au maximum 20 caractères")
     */
    private $nomRole;

    /**
     * @ORM\ManyToMany(targetEntity=User::class, mappedBy="role")
     */
    private $users;

    public function __construct()
    {
        $this->users = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomRoleFormatted()
    {
        return strtolower(str_replace("ROLE_","",$this->nomRole));
    }

    public function getNomRole(): ?string
    {
        return $this->nomRole;
    }

    public function setNomRole(string $nomRole): self
    {
        $this->nomRole = $nomRole;

        return $this;
    }

    /**
     * @return Collection|User[]
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(User $user): self
    {
        if (!$this->users->contains($user)) {
            $this->users[] = $user;
            $user->addRole($this);
        }

        return $this;
    }

    public function removeUser(User $user): self
    {
        if ($this->users->removeElement($user)) {
            $user->removeRole($this);
        }

        return $this;
    }
}

src/Form/RoleType.php
<?php

namespace App\Form;

use App\Entity\Role;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;

class RoleType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nomRole',TextType::class,[
                'label' => "Nom"
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Role::class,
        ]);
    }
}

src/Controller/RoleController.php
<?php

namespace App\Controller;

use App\Entity\Role;
use App\Form\RoleType;
use App\Repository\RoleRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/role")
 */
class RoleController extends AbstractController
{
    /**
     * @Route("/", name="role_index", methods={"GET"})
     */
    public function index(RoleRepository $roleRepository): Response
    {
        return $this->render('role/index.html.twig', [
            'roles' => $roleRepository->findAll(),
        ]);
    }

    /**
     * @Route("/nouveau", name="role_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $role = new Role();
        $form = $this->createForm(RoleType::class, $role);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($role);
            $entityManager->flush();
            $this->addFlash('success','Role ajouté avec succès');
            return $this->redirectToRoute('role_index');
        }

        return $this->render('role/new.html.twig', [
            'role' => $role,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}/edit", name="role_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Role $role): Response
    {
        $form = $this->createForm(RoleType::class, $role);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();
            $this->addFlash('success','Role modifié avec succès');
            return $this->redirectToRoute('role_index');
        }

        return $this->render('role/edit.html.twig', [
            'role' => $role,
        ]);
    }

    /**
     * @Route("/{id}", name="role_delete")
     */
    public function delete(Role $role): Response
    {
        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->remove($role);
        $entityManager->flush();
        $this->addFlash('success','Role supprimé avec succès');
        return $this->redirectToRoute('role_index');
    }
}

templates/role/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modif role{% endblock %}

{% block body %}
    <div class="container">
        <h3 class="text-center mt-2">Modification d'un rôle</h3>
        {{ form_start(form) }}
            {{ form_widget(form) }}
            <button class="btn btn-success">Modifier</button>
            <a href="{{ path('role_index') }}" class="btn btn-warning">Retourner</a>
        {{ form_end(form) }}
    </div>
{% endblock %}

templates/role/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des roles{% endblock %}

{% block body %}
    <div class="container">
        <h3 class="text-center mt-3">Liste des roles</h3>
        <a href="{{ path('role_new') }}" class="btn btn-primary mb-2">Nouveau</a>
        {% include "partials/notification.html.twig" %}
        
        <table class="table" id="example">
            <thead>
                <tr>
                    <th>Nom</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for role in roles %}
                    <tr>
                        <td>{{ role.nomRoleFormatted | title }}</td>
                        <td>
                            <a href="{{ path('role_edit', {'id': role.id}) }}" class="btn btn-info">Editer</a>
                            <a href="{{ path('role_delete', {'id': role.id}) }}" class="btn btn-danger">Supprimer</a>
                        </td>
                    </tr>
                {% else %}
                    <tr align="center">
                        <td colspan="2">Aucun role</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    {% include "partials/footer.html.twig" %}
{% endblock %}

templates/role/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouveau role{% endblock %}

{% block body %}
    <div class="container">
        <h3 class="text-center mt-2">Enregistrement d'un rôle</h3>
        {{ form_start(form) }}
            {{ form_widget(form) }}
            <button class="btn btn-primary">Enregistrer</button>
            <a href="{{ path('role_index') }}" class="btn btn-warning">Retourner</a>
        {{ form_end(form) }}
    </div>
{% endblock %}